### ISSUE TITLE
Tests (and maybe more) busted on Ruby 2.2.x

### ISSUE THREAD

**Issue by oreoshake** [twitter/secureheaders#155]
```
[Neils-MacBook-Pro-3 secureheaders (master *=)]$ ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
[Neils-MacBook-Pro-3 secureheaders (master *=)]$ be rspec
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.
......................................FFF..FFF.....................................................................................................................................

Failures:

  1) SecureHeaders::ContentSecurityPolicy#value when using a nonce adds a nonce and unsafe-inline to the script-src value when using chrome
     Failure/Error: header = ContentSecurityPolicy.new(default_opts.merge(:script_src => "self nonce"), :request => request_for(CHROME))
     RuntimeError:
       can't modify frozen NilClass
     # ./lib/secure_headers/headers/content_security_policy.rb:55:in `instance_variable_set'
     # ./lib/secure_headers/headers/content_security_policy.rb:55:in `set_nonce'
     # ./lib/secure_headers/headers/content_security_policy.rb:210:in `translate_dir_value'
     # ./lib/secure_headers/headers/content_security_policy.rb:116:in `block (2 levels) in initialize'
     # ./lib/secure_headers/headers/content_security_policy.rb:115:in `map'
     # ./lib/secure_headers/headers/content_security_policy.rb:115:in `block in initialize'
     # ./lib/secure_headers/headers/content_security_policy.rb:109:in `each'
     # ./lib/secure_headers/headers/content_security_policy.rb:109:in `inject'
     # ./lib/secure_headers/headers/content_security_policy.rb:109:in `initialize'
     # ./spec/lib/secure_headers/headers/content_security_policy_spec.rb:189:in `new'
     # ./spec/lib/secure_headers/headers/content_security_policy_spec.rb:189:in `block (4 levels) in <module:SecureHeaders>'

  2) SecureHeaders::ContentSecurityPolicy#value when using a nonce adds a nonce and unsafe-inline to the script-src value when using firefox
     Failure/Error: header = ContentSecurityPolicy.new(default_opts.merge(:script_src => "self nonce"), :request => request_for(FIREFOX))
     RuntimeError:
       can't modify frozen NilClass
     # ./lib/secure_headers/headers/content_security_policy.rb:55:in `instance_variable_set'
     # ./lib/secure_headers/headers/content_security_policy.rb:55:in `set_nonce'
     # ./lib/secure_headers/headers/content_security_policy.rb:210:in `translate_dir_value'
     # ./lib/secure_headers/headers/content_security_policy.rb:116:in `block (2 levels) in initialize'
     # ./lib/secure_headers/headers/content_security_policy.rb:115:in `map'
     # ./lib/secure_headers/headers/content_security_policy.rb:115:in `block in initialize'
     # ./lib/secure_headers/headers/content_security_policy.rb:109:in `each'
     # ./lib/secure_headers/headers/content_security_policy.rb:109:in `inject'
     # ./lib/secure_headers/headers/content_security_policy.rb:109:in `initialize'
     # ./spec/lib/secure_headers/headers/content_security_policy_spec.rb:194:in `new'
     # ./spec/lib/secure_headers/headers/content_security_policy_spec.rb:194:in `block (4 levels) in <module:SecureHeaders>'

  3) SecureHeaders::ContentSecurityPolicy#value when using a nonce adds a nonce and unsafe-inline to the script-src value when using opera
     Failure/Error: header = ContentSecurityPolicy.new(default_opts.merge(:script_src => "self nonce"), :request => request_for(OPERA))
     RuntimeError:
       can't modify frozen NilClass
     # ./lib/secure_headers/headers/content_security_policy.rb:55:in `instance_variable_set'
     # ./lib/secure_headers/headers/content_security_policy.rb:55:in `set_nonce'
     # ./lib/secure_headers/headers/content_security_policy.rb:210:in `translate_dir_value'
     # ./lib/secure_headers/headers/content_security_policy.rb:116:in `block (2 levels) in initialize'
     # ./lib/secure_headers/headers/content_security_policy.rb:115:in `map'
     # ./lib/secure_headers/headers/content_security_policy.rb:115:in `block in initialize'
     # ./lib/secure_headers/headers/content_security_policy.rb:109:in `each'
     # ./lib/secure_headers/headers/content_security_policy.rb:109:in `inject'
     # ./lib/secure_headers/headers/content_security_policy.rb:109:in `initialize'
     # ./spec/lib/secure_headers/headers/content_security_policy_spec.rb:199:in `new'
     # ./spec/lib/secure_headers/headers/content_security_policy_spec.rb:199:in `block (4 levels) in <module:SecureHeaders>'

  4) SecureHeaders::ContentSecurityPolicy#value when using a nonce adds a nonce and unsafe-inline to the style-src value
     Failure/Error: header = ContentSecurityPolicy.new(default_opts.merge(:style_src => "self nonce"), :request => request_for(CHROME))
     RuntimeError:
       can't modify frozen NilClass
     # ./lib/secure_headers/headers/content_security_policy.rb:55:in `instance_variable_set'
     # ./lib/secure_headers/headers/content_security_policy.rb:55:in `set_nonce'
     # ./lib/secure_headers/headers/content_security_policy.rb:210:in `translate_dir_value'
     # ./lib/secure_headers/headers/content_security_policy.rb:116:in `block (2 levels) in initialize'
     # ./lib/secure_headers/headers/content_security_policy.rb:115:in `map'
     # ./lib/secure_headers/headers/content_security_policy.rb:115:in `block in initialize'
     # ./lib/secure_headers/headers/content_security_policy.rb:109:in `each'
     # ./lib/secure_headers/headers/content_security_policy.rb:109:in `inject'
     # ./lib/secure_headers/headers/content_security_policy.rb:109:in `initialize'
     # ./spec/lib/secure_headers/headers/content_security_policy_spec.rb:216:in `new'
     # ./spec/lib/secure_headers/headers/content_security_policy_spec.rb:216:in `block (4 levels) in <module:SecureHeaders>'

  5) SecureHeaders::ContentSecurityPolicy#value when using a nonce adds an identical nonce to the style and script-src directives
     Failure/Error: header = ContentSecurityPolicy.new(default_opts.merge(:style_src => "self nonce", :script_src => "self nonce"), :request => request_for(CHROME))
     RuntimeError:
       can't modify frozen NilClass
     # ./lib/secure_headers/headers/content_security_policy.rb:55:in `instance_variable_set'
     # ./lib/secure_headers/headers/content_security_policy.rb:55:in `set_nonce'
     # ./lib/secure_headers/headers/content_security_policy.rb:210:in `translate_dir_value'
     # ./lib/secure_headers/headers/content_security_policy.rb:116:in `block (2 levels) in initialize'
     # ./lib/secure_headers/headers/content_security_policy.rb:115:in `map'
     # ./lib/secure_headers/headers/content_security_policy.rb:115:in `block in initialize'
     # ./lib/secure_headers/headers/content_security_policy.rb:109:in `each'
     # ./lib/secure_headers/headers/content_security_policy.rb:109:in `inject'
     # ./lib/secure_headers/headers/content_security_policy.rb:109:in `initialize'
     # ./spec/lib/secure_headers/headers/content_security_policy_spec.rb:221:in `new'
     # ./spec/lib/secure_headers/headers/content_security_policy_spec.rb:221:in `block (4 levels) in <module:SecureHeaders>'

  6) SecureHeaders::ContentSecurityPolicy#value when using a nonce does not add 'unsafe-inline' twice
     Failure/Error: header = ContentSecurityPolicy.new(default_opts.merge(:script_src => "self nonce inline"), :request => request_for(CHROME))
     RuntimeError:
       can't modify frozen NilClass
     # ./lib/secure_headers/headers/content_security_policy.rb:55:in `instance_variable_set'
     # ./lib/secure_headers/headers/content_security_policy.rb:55:in `set_nonce'
     # ./lib/secure_headers/headers/content_security_policy.rb:210:in `translate_dir_value'
     # ./lib/secure_headers/headers/content_security_policy.rb:116:in `block (2 levels) in initialize'
     # ./lib/secure_headers/headers/content_security_policy.rb:115:in `map'
     # ./lib/secure_headers/headers/content_security_policy.rb:115:in `block in initialize'
     # ./lib/secure_headers/headers/content_security_policy.rb:109:in `each'
     # ./lib/secure_headers/headers/content_security_policy.rb:109:in `inject'
     # ./lib/secure_headers/headers/content_security_policy.rb:109:in `initialize'
     # ./spec/lib/secure_headers/headers/content_security_policy_spec.rb:229:in `new'
     # ./spec/lib/secure_headers/headers/content_security_policy_spec.rb:229:in `block (4 levels) in <module:SecureHeaders>'
```
